### ISSUE TITLE
how can I use Daubechies 8?

### ISSUE THREAD

**Issue by mmmmayi** [WUCIS-TemporalDataMining/DaubechiesWaveletTransform#1]
hello, i want to ask how can i use db8?

**Comment by r4dat** [comment]
This repository was for a research project a number of years ago and only ever intended to implement a daubechies 4 wavelet.

There are a number of more generalized software implementations available. 
Matlab has a built in transform, there is the Pywavelets package, as well as Haifeng's java implementation in [SMILE](https://github.com/haifengl/smile).

If the original paper is too formal then a more recent applied paper is "Low-Cost Lifting Architecture and Lossless Implementation of Daubechies-8 Wavelets" by Hasan et al.
